@startuml

actor Browser
box Server
participant HttpServer
participant QuestionPostController
participant OptionPostController
participant controllers
end box
participant QuestionDao
participant AnswerDao
database exam_survey_db

Browser --> HttpServer: POST /api/newQuestion
HttpServer -> controllers: get("/api/newQuestion")
HttpServer <-- controllers: QuestionPostController
HttpServer -> QuestionPostController: handle
QuestionPostController -> QuestionPostController: question = new Question()
QuestionPostController -> QuestionPostController: question.setName(parameters.get("name"))
QuestionPostController -> QuestionDao: save(question)
QuestionDao -> exam_survey_db: INSERT INTO QUESTION...
Browser <-- HttpServer: HTTP/1.1 303 See also \r Location: /addQuestion.html
Browser --> HttpServer: POST /api/addOptions
HttpServer -> controllers: get("/api/addOptions")
HttpServer <-- controllers: OptionPostController
HttpServer -> OptionPostController: handle
OptionPostController -> OptionPostController: answer = new Answer()
OptionPostController -> OptionPostController: answer.setName(parameters.get("option"))
OptionPostController -> OptionPostController: answer.setQuestionId(questionDao.retrieveIdByName(parameters.get("questions")))
OptionPostController -> AnswerDao: save(answer)
AnswerDao -> exam_survey_db: INSERT INTO ANSWER...
Browser <-- HttpServer: HTTP/1.1 303 See also \r Location: /addQuestion.html


@enduml